export const profesionales = [
  {
    id: 1,
    nombre: "Roberto Carlos",
    oficio: "Plomero",
    calificacion: 4.7,
    trabajosRealizados: 128,
    cobraPorHora: true,
    costoPorHora: 850.5,
    perfilVerificado: true,
    especialidades: ["instalaciones", "reparaciones", "fugas de gas"],
  },
  {
    id: 2,
    nombre: "Juana Molina",
    oficio: "Electricista",
    calificacion: 4.9,
    trabajosRealizados: 215,
    cobraPorHora: true,
    costoPorHora: 1100.0,
    perfilVerificado: true,
    especialidades: ["tableros", "instalaciones", "iluminación led"],
  },
  {
    id: 3,
    nombre: "Miguel Ángel",
    oficio: "Pintor",
    calificacion: 4.5,
    trabajosRealizados: 89,
    cobraPorHora: false,
    costoPorHora: null, // Cobra por proyecto
    perfilVerificado: true,
    especialidades: ["interiores", "exteriores", "revestimientos"],
  },
  {
    id: 4,
    nombre: "Laura Pausini",
    oficio: "Plomero",
    calificacion: 4.2,
    trabajosRealizados: 75,
    cobraPorHora: true,
    costoPorHora: 780.0,
    perfilVerificado: false,
    especialidades: ["destapaciones", "grifería"],
  },
  {
    id: 5,
    nombre: "Ricardo Arjona",
    oficio: "Gasista",
    calificacion: 3.8,
    trabajosRealizados: 55,
    cobraPorHora: true,
    costoPorHora: 950.0,
    perfilVerificado: true,
    especialidades: ["reparaciones", "inspecciones", "fugas de gas"],
  },
];
